### ISSUE TITLE
PublishWithConfirmation infinte loop

### ISSUE THREAD

**Issue by dfelici87** [houseofcat/turbocookedrabbit#15]
Hi,

I use PublishWithConfirmation function but if rabbit return an error (confirmation.Ack = false) the function enter into an infinite loop because  there is a "goto Publish" statement that reset the timeout and re-publish a message every times.

It's correct? or It's a bug?
Can you manage attempts? 

thanks

**Comment by houseofcat** [comment]
It's correct, `confirmation.Ack == false` means that the server is telling us it did not get the message and that we need to resend it.

This could in theory be an infinite loop the server kept replying `false` but that sounds like a server side issue.

PublishWithConfirmation is working as intended the goal being to try its best to get the message server side.

**Comment by ppiccolo** [comment]
I can understand Your point but how can I catch this error ?

**Comment by houseofcat** [comment]
The infinite loop? Well you could write your own or switch to this one manual Publish method
```golang
func (pub *Publisher) PublishWithConfirmationContext(ctx context.Context, letter *Letter) {
```

It will stop trying after context you provide expires.

**Comment by ppiccolo** [comment]
Ok thank you, but how I can get back the channel error ? No way ?

**Comment by houseofcat** [comment]
Why would you need to do that? In golang you can step into the package and put a breakpoint?

If you mean after deployment and wanted to log such a message you have to get creative golang and writing a logging interface, or return the error out. This function is designed to keep retrying on error because reliable transmission is the highest priority _**here**_.

If you want Publish with errors, we output `err` via a `chan` that you can subscribe to and log all messages.
https://github.com/houseofcat/turbocookedrabbit/blob/ab307a1ac5fa0399b9c6ba40ba53565d1191b093/v2/pkg/tcr/publisher.go#L100

Also you can write your own version using components like the ChannelPool. You don't have to use the helpers I provided.

**Comment by ppiccolo** [comment]
> If you want Publish with errors, we output err via a chan that you can subscribe to and log all messages.
https://github.com/houseofcat/turbocookedrabbit/blob/ab307a1ac5fa0399b9c6ba40ba53565d1191b093/v2/pkg/tcr/publisher.go#L100


this is exactly what i'm trying to achieve, but if i send a message to a non existing queue no error are returned in the exposed chan

**Comment by houseofcat** [comment]
PublishWithConfirmation is just loop on Publish.

Switch to Publish.
https://github.com/houseofcat/turbocookedrabbit/blob/ab307a1ac5fa0399b9c6ba40ba53565d1191b093/v2/pkg/tcr/publisher.go#L78

**Comment by ppiccolo** [comment]
> If you want Publish with errors try one of the simpler publish functions. Here, for example, we output err via a chan that you can subscribe to and log all messages.

This is exactly what I'm trying to do but if I try to publish a message to a non existing exchange I'm not getting back any error on the chan that you provide maybe due to the fact that undeliverable message are returned to Channel.NotifyReturn ?

https://github.com/streadway/amqp/blob/e6b33f460591b0acb2f13b04ef9cf493720ffe17/channel.go#L1300

but maybe I'm missing something...

```
package main

import (
	log "github.com/sirupsen/logrus"
	turbo "github.com/houseofcat/turbocookedrabbit/v2/pkg/tcr"
	"time"
)

func ErrorHandler(err error){
	log.Errorf("Error: %v", err)
}

func main() {

	cfg := &turbo.RabbitSeasoning{
		EncryptionConfig:  &turbo.EncryptionConfig{
			Enabled:           false,
			Type:              "",
			Hashkey:           nil,
			TimeConsideration: 0,
			MemoryMultiplier:  0,
			Threads:           0,
		},
		CompressionConfig: &turbo.CompressionConfig{
			Enabled: false,
			Type:    "",
		},
		PoolConfig:        &turbo.PoolConfig{
			ApplicationName:      "test_error",
			URI:                  "amqp://guest:guest@x.x.x.x:5672/",
			Heartbeat:            1,
			ConnectionTimeout:    10,
			SleepOnErrorInterval: 1,
			MaxConnectionCount:   100,
			MaxCacheChannelCount: 100,
			TLSConfig:            nil,
		},
		ConsumerConfigs:   nil,
		PublisherConfig:   &turbo.PublisherConfig{
			AutoAck:                false,
			SleepOnIdleInterval:    1,
			SleepOnErrorInterval:   1,
			PublishTimeOutInterval: 1,
			MaxRetryCount:          2,
		},
	}
	svc, err := turbo.NewRabbitService(cfg, "","", nil, ErrorHandler)

	if err != nil {
		log.Fatalf("%v", err)
	}

	go func() {

		for {
			select {
			case err := <-svc.CentralErr():
				log.Errorf("Error %v", err)
			case recipt := <-svc.Publisher.PublishReceipts():
				if recipt.Error != nil {
					log.Errorf("Error %v", recipt.ToString())
					break
				}
				log.Infof("Info %v", recipt.ToString())
			default:
				time.Sleep(10 * time.Microsecond)
				break
			}
		}
	}()

	log.Infof("%v", "publishing...")

	for i := 0; i < 100; i++ {
		err = svc.Publish("Hi", "nothing", "nothing", "", true, nil)
		if err != nil {
			log.Fatalf("%v", err)
		}
	}
	
	time.Sleep(10 * time.Second)

	log.Infof("%v", "Done")
}
```

however I'm agree with you that the behavior of  PublishWithConfirmation is correct and the suggestion you given can fit the requirements.

Maybe this could be another issue.

Thanks.

**Comment by houseofcat** [comment]
I believe what you are experiencing is a Dead Letter Queueing.

This test publishes to an exchange that doesn't exist.
```golang
// TestBasicPublishToNonExistentExchange tests what happen when a publish to exchange
// that doesn't exist also doesn't error.
func TestBasicPublishToNonExistentExchange(t *testing.T) {
	defer leaktest.Check(t)()

	letter := tcr.CreateMockLetter("DoesNotExist", "TcrTestQueue", nil)
	amqpConn, err := amqp.Dial(Seasoning.PoolConfig.URI)
	if err != nil {
		t.Error(t, err)
		return
	}

	amqpChan, err := amqpConn.Channel()
	if err != nil {
		t.Error(t, err)
		return
	}

	err = amqpChan.Publish(
		letter.Envelope.Exchange,
		letter.Envelope.RoutingKey,
		letter.Envelope.Mandatory,
		letter.Envelope.Immediate,
		amqp.Publishing{
			ContentType: letter.Envelope.ContentType,
			Body:        letter.Body,
			MessageId:   letter.LetterID.String(),
			Timestamp:   time.Now().UTC(),
			AppId:       "TCR-Test",
		})

	if err != nil {
		t.Error(t, err)
		return
	}

	amqpChan.Close()
	amqpConn.Close()
}
```

As you can see the test doesn't exit out early.
![image](https://user-images.githubusercontent.com/1414138/115090282-72c14b80-9ee2-11eb-8098-2fad56e1b891.png)

And that exchange does not exist.
![image](https://user-images.githubusercontent.com/1414138/115090320-866cb200-9ee2-11eb-9edc-0971088228f3.png)

And therefore no error.

The reason it loops in a PublishWithConfirmation call is because I get a second message the message was not properly received server side at its destination - which is correct.

**Comment by ppiccolo** [comment]
> Edit: I am starting to have my doubts though. I would normally expect this to error like it does in C#.

Definitely this is my expectation too... need further investigation

**Comment by houseofcat** [comment]
@ppiccolo Hey Paolo, simple temporary work around is to use the Publish or PublishWithConfirmationContext for right now. I believe the issue is that somewhere, somehow, it's not following AMQP v0.9.1 spec in `streadway/amqp`. I have opened an issue with them and will keep this open to monitor the situation.

https://github.com/streadway/amqp/issues/504

**Comment by ppiccolo** [comment]
Ok, tnx a lot.
